[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.4"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "2.1.5"
tempfile = "3.10.1"
rand = "0.8.5"
